// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#define PIN_nSYNC 18
#define PIN_nDIN 16
#define PIN_nRPLY 17

// ----------- //
// mpi_capture //
// ----------- //

#define mpi_capture_wrap_target 0
#define mpi_capture_wrap 2
#define mpi_capture_pio_version 1

static const uint16_t mpi_capture_program_instructions[] = {
            //     .wrap_target
    0x20b2, //  0: wait   1 pin, 18
    0x2032, //  1: wait   0 pin, 18
    0x4018, //  2: in     pins, 24
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program mpi_capture_program = {
    .instructions = mpi_capture_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = mpi_capture_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config mpi_capture_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + mpi_capture_wrap_target, offset + mpi_capture_wrap);
    return c;
}
#endif

// ----------- //
// mpi_respond //
// ----------- //

#define mpi_respond_wrap_target 0
#define mpi_respond_wrap 13
#define mpi_respond_pio_version 1

static const uint16_t mpi_respond_program_instructions[] = {
            //     .wrap_target
    0xa0e3, //  0: mov    osr, null
    0x6098, //  1: out    pindirs, 24
    0x80a0, //  2: pull   block
    0x2030, //  3: wait   0 pin, 16
    0x6018, //  4: out    pins, 24
    0xa0e1, //  5: mov    osr, x
    0x6098, //  6: out    pindirs, 24
    0xbf42, //  7: nop                           [31]
    0xbf42, //  8: nop                           [31]
    0x4018, //  9: in     pins, 24
    0xa0e2, // 10: mov    osr, y
    0x6098, // 11: out    pindirs, 24
    0x20b0, // 12: wait   1 pin, 16
    0xc000, // 13: irq    nowait 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program mpi_respond_program = {
    .instructions = mpi_respond_program_instructions,
    .length = 14,
    .origin = -1,
    .pio_version = mpi_respond_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config mpi_respond_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + mpi_respond_wrap_target, offset + mpi_respond_wrap);
    return c;
}
#endif

// ------------------ //
// mpi_respond_assist //
// ------------------ //

#define mpi_respond_assist_wrap_target 0
#define mpi_respond_assist_wrap 18
#define mpi_respond_assist_pio_version 1

static const uint16_t mpi_respond_assist_program_instructions[] = {
            //     .wrap_target
    0xa0e3, //  0: mov    osr, null
    0x6098, //  1: out    pindirs, 24
    0x80a0, //  2: pull   block
    0x2030, //  3: wait   0 pin, 16
    0x6018, //  4: out    pins, 24
    0xa0e1, //  5: mov    osr, x
    0x6098, //  6: out    pindirs, 24
    0xbf42, //  7: nop                           [31]
    0xbf42, //  8: nop                           [31]
    0xa0e2, //  9: mov    osr, y
    0x6098, // 10: out    pindirs, 24
    0x20b0, // 11: wait   1 pin, 16
    0xc000, // 12: irq    nowait 0
    0xe001, // 13: set    pins, 1
    0xa0e6, // 14: mov    osr, isr
    0x6098, // 15: out    pindirs, 24
    0xbf42, // 16: nop                           [31]
    0xaf42, // 17: nop                           [15]
    0xe080, // 18: set    pindirs, 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program mpi_respond_assist_program = {
    .instructions = mpi_respond_assist_program_instructions,
    .length = 19,
    .origin = -1,
    .pio_version = mpi_respond_assist_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config mpi_respond_assist_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + mpi_respond_assist_wrap_target, offset + mpi_respond_assist_wrap);
    return c;
}

#include "hardware/clocks.h"
static inline void mpi_capture_init(PIO pio, uint sm, uint offset) {
    pio_sm_config c = mpi_capture_program_get_default_config(offset);
    sm_config_set_in_pins(&c, 0);
    sm_config_set_in_shift(&c, false /* shift left */, true /* autopush */, 24);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    sm_config_set_clkdiv(&c, 1.0f);
    pio_sm_init(pio, sm, offset, &c);
}
static inline void mpi_respond_init(PIO pio, uint sm, uint offset,
                                    uint32_t dirs_ad, uint32_t dirs_ad_rply) {
#if MPI_RPLY_ASSIST
    pio_sm_config c = mpi_respond_assist_program_get_default_config(offset);
    sm_config_set_set_pins(&c, PIN_nRPLY, 1);   // the assisted release drives it
#else
    pio_sm_config c = mpi_respond_program_get_default_config(offset);
#endif
    sm_config_set_in_pins(&c, 0);       // so WAIT PIN indices are GPIO numbers
    sm_config_set_out_pins(&c, 0, 24);
    sm_config_set_out_shift(&c, true /* shift right */, false /* no autopull */, 32);
    // Readback of the driven bus, autopushed like the capture machine so the
    // two arrive in the same 24-bit form.  The FIFO is no longer joined to TX:
    // four entries each is ample when the CPU drains one per cycle.
    sm_config_set_in_shift(&c, false /* shift left */, true /* autopush */, 24);
    sm_config_set_clkdiv(&c, 1.0f);
    pio_sm_init(pio, sm, offset, &c);
    // Preload the two direction masks into X and Y.
    pio_sm_put_blocking(pio, sm, dirs_ad);
    pio_sm_exec(pio, sm, pio_encode_pull(false, false));
    pio_sm_exec(pio, sm, pio_encode_mov(pio_x, pio_osr));
    pio_sm_put_blocking(pio, sm, dirs_ad_rply);
    pio_sm_exec(pio, sm, pio_encode_pull(false, false));
    pio_sm_exec(pio, sm, pio_encode_mov(pio_y, pio_osr));
#if MPI_RPLY_ASSIST
    // ...and a third into ISR: nRPLY driven, AD lines released.  The assisted
    // release needs to let go of the AD lines while still holding nRPLY, which
    // neither of the other two masks can express.
    pio_sm_put_blocking(pio, sm, dirs_ad_rply & ~dirs_ad);
    pio_sm_exec(pio, sm, pio_encode_pull(false, false));
    pio_sm_exec(pio, sm, pio_encode_mov(pio_isr, pio_osr));
#endif
}

#endif

