#!/usr/bin/env python3
"""Build firmware/rom_images.c from one or more 1801RE2 dumps.

Each dump is converted out of programmer order (see re2_convert.py) and emitted
as a 4096-word array in CPU order.  The chip code stored in the dump trailer
decides which 8 KB window the image answers for; pass --code to override it.

    ./gen_rom_images.py -o ../../firmware/rom_images.c 017_bk0010.rom 106_bk0010.rom
"""

import argparse
import re
import sys
from pathlib import Path

from re2_convert import CODE_TO_BASE, convert, split_dump, words

# The self-test pattern is an instrument -- it tests the board's own wiring
# rather than carrying anything the machine wants to run -- so it lives with the
# other diagnostics.  This generator is where the two halves of the repository
# meet: --selftest emits that pattern into the same rom_images.c a real dump
# would produce, and the firmware cannot tell the difference.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "diag"))

import selftest  # noqa: E402


def emit_selftest(output: Path, full_window: bool) -> int:
    """All eight windows filled with the self-identifying pattern."""
    out = ["// Generated by tools/gen_rom_images.py --selftest -- do not edit.",
           "//",
           "// Self-test patterns, not ROM contents. Each word encodes its own",
           "// index and the window it belongs to, so a dump taken through a ROM",
           "// reader can be checked with tools/check_selftest.py and will say",
           "// which address or data line is wrong rather than merely that",
           "// something is.",
           "", '#include "rom_images.h"', ""]
    entries = []
    for code in range(8):
        base = CODE_TO_BASE[code]
        w = selftest.image(code)
        count = len(w)
        if code == 0 and not full_window:
            count = (0o177000 - 0o160000) // 2
        name = f"selftest_{code}"
        out.append(f"// code {code:o}: {base:06o}, self-test pattern")
        out.append(f"static const uint16_t {name}[{len(w)}] = {{")
        for j in range(0, len(w), 8):
            out.append("    " + ", ".join(f"0x{x:04X}" for x in w[j:j + 8]) + ",")
        out.append("};")
        out.append("")
        entries.append(f'    {{ "selftest{code}", {code}, {count}, {name} }},')

    out.append("const mpi_image_t mpi_images[] = {")
    out.extend(entries)
    out.append("};")
    out.append("")
    out.append("const unsigned mpi_image_count = "
               "sizeof(mpi_images) / sizeof(mpi_images[0]);")
    out.append("")
    output.write_text("\n".join(out))
    print(f"wrote {output}: self-test patterns for all 8 windows")
    return 0


def emit_logical(image: Path, output: Path) -> int:
    """One 32256-byte CPU-order image, based at 100000, split by window.

    This is the shape a test ROM is written in -- one flat program spanning the
    whole address space the four chips cover -- and the shape ukncbtl loads, so
    the same file can be tried in the emulator before it goes near hardware.
    Chip order does not enter into it: no conversion, no trailers, just the
    address arithmetic.
    """
    raw = image.read_bytes()
    want = 0o100000 - 0o1000
    if len(raw) != want:
        print(f"error: {image.name} is {len(raw)} bytes, expected {want}",
              file=sys.stderr)
        return 1

    out = [f"// Generated by tools/gen_rom_images.py --logical {image.name}"
           " -- do not edit.", "",
           '#include "rom_images.h"', ""]
    entries = []
    # Windows in address order; the last stops short of the I/O page.
    for code, base in ((3, 0o100000), (2, 0o120000), (1, 0o140000), (0, 0o160000)):
        off = base - 0o100000
        count = min(4096, (len(raw) - off) // 2)
        w = [raw[off + 2 * i] | (raw[off + 2 * i + 1] << 8) for i in range(count)]
        name = f"img_logical_{code}"
        top = base + 2 * count - 1
        out.append(f"// code {code:o}: {base:06o}-{top:06o} octal, from {image.name}")
        out.append(f"static const uint16_t {name}[{count}] = {{")
        for j in range(0, count, 8):
            out.append("    " + ", ".join(f"0x{x:04X}" for x in w[j:j + 8]) + ",")
        out.append("};")
        out.append("")
        entries.append(f'    {{ "{image.stem}_{code}", {code}, {count}, {name} }},')

    out.append("const mpi_image_t mpi_images[] = {")
    out.extend(entries)
    out.append("};")
    out.append("")
    out.append("const unsigned mpi_image_count = "
               "sizeof(mpi_images) / sizeof(mpi_images[0]);")
    out.append("")
    output.write_text("\n".join(out))
    print(f"wrote {output}: {image.name} split across 4 windows")
    return 0


def ident(path: Path) -> str:
    name = re.sub(r"[^0-9a-zA-Z]+", "_", path.stem).strip("_").lower()
    return "img_" + (name if name and not name[0].isdigit() else "re2_" + name)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dumps", nargs="*", type=Path)
    ap.add_argument("-o", "--output", type=Path, required=True)
    ap.add_argument("--code", type=int, action="append", default=[],
                    help="override the chip code, once per dump, in order")
    ap.add_argument("--full-window", action="store_true",
                    help="serve all 4096 words of a code 0 image.  By default "
                         "it stops at 3840, leaving 177000-177777 to the I/O "
                         "page -- which is what the UKNC needs")
    ap.add_argument("--selftest", action="store_true",
                    help="ignore the dumps and emit self-identifying test "
                         "patterns for all eight windows, for reading back "
                         "through a ROM dumper. See tools/selftest.py")
    ap.add_argument("--logical", type=Path,
                    help="take one 32256-byte image in CPU order based at "
                         "100000 and split it across the four windows -- the "
                         "form make_testrom.py and make_ramtest.py emit, and "
                         "the form ukncbtl loads")
    args = ap.parse_args()

    if args.selftest:
        return emit_selftest(args.output, args.full_window)
    if args.logical:
        return emit_logical(args.logical, args.output)
    if not args.dumps:
        print("error: give at least one dump, or --selftest", file=sys.stderr)
        return 1
    if args.code and len(args.code) != len(args.dumps):
        print("error: --code must be given once per dump, or not at all",
              file=sys.stderr)
        return 1

    out = ["// Generated by tools/gen_rom_images.py -- do not edit.", "",
           '#include "rom_images.h"', ""]
    entries, seen = [], {}

    for i, path in enumerate(args.dumps):
        body, trailer_code = split_dump(path.read_bytes())
        code = args.code[i] if args.code else trailer_code
        if code is None:
            print(f"error: {path.name} has no chip code; pass --code",
                  file=sys.stderr)
            return 1
        code &= 7
        if code in seen:
            print(f"error: {path.name} and {seen[code]} both claim window "
                  f"{CODE_TO_BASE[code]:06o}", file=sys.stderr)
            return 1
        seen[code] = path.name

        name = ident(path)
        w = words(convert(body))
        base = CODE_TO_BASE[code]

        # Code 0 covers 160000-177777, but the top 512 bytes are the PDP-11 I/O
        # page.  Replying there means fighting the machine's own registers for
        # the bus, so stop short unless explicitly told not to.
        word_count = len(w)
        if code == 0 and not args.full_window:
            word_count = (0o177000 - 0o160000) // 2      # 3840
            top = base + word_count * 2 - 1
        else:
            top = base + 0o17777

        out.append(f"// {path.name}: code {code:o}, {base:06o}-{top:06o} octal"
                   f"{'' if word_count == len(w) else '  (I/O page left free)'}")
        out.append(f"static const uint16_t {name}[{len(w)}] = {{")
        for j in range(0, len(w), 8):
            out.append("    " + ", ".join(f"0x{x:04X}" for x in w[j:j + 8]) + ",")
        out.append("};")
        out.append("")
        entries.append(f'    {{ "{path.stem}", {code}, {word_count}, {name} }},')

    out.append("const mpi_image_t mpi_images[] = {")
    out.extend(entries)
    out.append("};")
    out.append("")
    out.append("const unsigned mpi_image_count = "
               "sizeof(mpi_images) / sizeof(mpi_images[0]);")
    out.append("")

    args.output.write_text("\n".join(out))
    print(f"wrote {args.output}: {len(entries)} image(s), "
          f"windows {sorted(oct(c)[2:] for c in seen)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
