#!/usr/bin/env python3
"""Convert 1801RE2 mask ROM dumps between programmer order and CPU order.

The dumps published in the 1801BM1/k1801 archive are in "Sterkh programmer"
order: every data byte is bit-inverted and the 16-bit word addresses are
inverted too.  Reduced to a single byte-level operation, as implemented by the
original rev16 utility (rev16/rev16.c, EXE_Convert):

    out[addr ^ 0x1FFE] = ~in[addr]

0x1FFE inverts byte-address bits 1..12, i.e. the twelve word-address bits,
leaving bit 0 (the byte-within-word selector) alone.  The transform is its own
inverse, so the same function converts in both directions.

Dump files carry two extra trailing bytes: the chip "code" (which 8 KB window
of the 64 KB address space the chip answers to) and a constant 0x03.
"""

import argparse
import struct
import sys
from pathlib import Path

ROM_BYTES = 0x2000          # 4096 words x 16 bits
ADDR_MASK = ROM_BYTES - 2   # 0x1FFE
TRAILER_LEN = 2

# Chip "code" -> base address of the 8 KB window, in octal, per the k1801
# archive's table.  The code is the value the chip's decoder compares the top
# three address bits against; note it is inverted with respect to the address.
CODE_TO_BASE = {
    0o0: 0o160000,
    0o1: 0o140000,
    0o2: 0o120000,
    0o3: 0o100000,
    0o4: 0o060000,
    0o5: 0o040000,
    0o6: 0o020000,
    0o7: 0o000000,
}


def convert(data: bytes) -> bytes:
    """Apply the rev16 transform.  Self-inverse."""
    if len(data) != ROM_BYTES:
        raise ValueError(f"expected {ROM_BYTES} bytes, got {len(data)}")
    out = bytearray(ROM_BYTES)
    for addr in range(ROM_BYTES):
        out[addr ^ ADDR_MASK] = (~data[addr]) & 0xFF
    return bytes(out)


def split_dump(raw: bytes):
    """Return (body, code) from a dump file, tolerating a missing trailer."""
    if len(raw) == ROM_BYTES + TRAILER_LEN:
        code, marker = raw[ROM_BYTES], raw[ROM_BYTES + 1]
        if marker != 0x03:
            print(f"warning: trailer marker is 0x{marker:02X}, expected 0x03",
                  file=sys.stderr)
        return raw[:ROM_BYTES], code
    if len(raw) == ROM_BYTES:
        return raw, None
    raise ValueError(f"unexpected dump length {len(raw)}")


def words(body: bytes):
    return struct.unpack("<%dH" % (ROM_BYTES // 2), body)


def looks_like_pdp11(body: bytes) -> dict:
    """Cheap plausibility check: count instructions that are common in real code.

    RTS PC (000207) and JSR PC,x (004767) essentially never occur by chance at
    the rate they occur in genuine PDP-11 code, so a converted image that shows
    dozens of each is almost certainly right way round.
    """
    w = words(body)
    return {
        "rts_pc": sum(1 for x in w if x == 0o000207),
        "jsr_pc": sum(1 for x in w if x == 0o004767),
        "mov_range": sum(1 for x in w if 0o010000 <= x < 0o020000),
    }


def emit_c_array(body: bytes, name: str, code, source: str) -> str:
    w = words(body)
    lines = [
        "// Generated by tools/re2_convert.py -- do not edit.",
        f"// Source: {source}",
        "",
        "#include <stdint.h>",
        "",
    ]
    if code is not None:
        base = CODE_TO_BASE[code & 7]
        lines.append(f"// Chip code {code & 7:o}: window {base:06o}-"
                     f"{base + 0o17777:06o} octal")
        lines.append(f"const uint8_t {name}_code = {code & 7};")
        lines.append("")
    lines.append(f"const uint16_t {name}[{len(w)}] = {{")
    for i in range(0, len(w), 8):
        chunk = ", ".join(f"0x{x:04X}" for x in w[i:i + 8])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", type=Path)
    ap.add_argument("-o", "--output", type=Path,
                    help="output file; omit to only report on the input")
    ap.add_argument("--format", choices=("bin", "c"), default="bin")
    ap.add_argument("--name", default="rom_image",
                    help="C identifier when --format c")
    args = ap.parse_args()

    raw = args.input.read_bytes()
    body, code = split_dump(raw)
    converted = convert(body)

    before = looks_like_pdp11(body)
    after = looks_like_pdp11(converted)
    print(f"{args.input.name}: code={'?' if code is None else oct(code)[2:]}")
    print(f"  as read   RTS PC={before['rts_pc']:4}  JSR PC={before['jsr_pc']:4}")
    print(f"  converted RTS PC={after['rts_pc']:4}  JSR PC={after['jsr_pc']:4}")
    if after["rts_pc"] < before["rts_pc"]:
        print("  warning: input already looks like CPU order", file=sys.stderr)

    if args.output:
        if args.format == "bin":
            args.output.write_bytes(converted)
        else:
            args.output.write_text(
                emit_c_array(converted, args.name, code, args.input.name))
        print(f"  wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
